insert into band (name, country, formed_in) values
	('Children of Bodom', 'Finland', 1997),
	('Norhland', 'Spain', 2004),
	('Kalmah', 'Finland', 1998),
	('Crimson Shadows', 'Canada', 2006),
	('Bonehunter', 'Finland', 2011),
	('Powerwolf', 'Germany', 2003),
	('Unleash the Archers', 'Canada', 2007),
	('Visigoth', 'United States of America', 2010);

insert into album (name, release_year, band_id) values
	('Something Wild', 1997, 1),
	('Downfall and Rebirth', 2015, 2),
	('Seventh Swamphony', 2013, 3),
	('Kings Among Men', 2014, 4),
	('Children of the Atom', 2018, 5),
	('The Sacrament of Sin', 2018, 6),
	('Apex', 2017, 7),
	('Conquerors\`s Oath', 2018, 8),
	('Hatebreeder', 1998, 1),
	('They Will Return', 2002, 3),
	('Blessed & Possesed', 2015, 6);

insert into song (name, duration, album_id) values
	('Deadnight Warrior', 3.21, 1),
	('When Nature Awakes', 5.06, 2),
	('Windlake Tale', 4.28, 3),
	('A Gathering of Kings', 5.28, 4),
	('Reek of Reaper` Scythe', 3.39, 5),
	('Incense and Iron', 3.57, 6),
	('False Walls', 8.05, 7),
	('Steel and Silver', 6.01, 8),
	('Downfall', 4.34, 9),
	('Human Fates', 5.50, 10),
	('Army of the Night', 3.23, 11),
	('March of Victory', 1.10, 4),
	('Freedom and Salvation', 4.42, 4),
	('Red Light in My Eyes', 3.50, 1),
	('Awakening', 7.17, 7);

insert into lyric (song_id, lyric) values
	(1, 'Before the daylight falls to the graves - deadnight shadows Soon I`ll cross through that rift I`ll fly across the sky It`s such a lonely way This one`ll be black The jet black always in the sky It reflects hatred in my eyes If the daylight dies the shadows fall all over me Then death, you`ll have your way Scorn the torment in moonlight`s shadow I can`t get out, lost the way for eternity You`re the guard of the dead ones In the night I`ll find you to drink your blood Still the deadnight`s screaming in my heart The dead of night`s close by! So wake it up, call my name, it`s Deadnight Warrior! Send them on a trip of pain I can`t wait! It`s such a lonely fight This one`ll black The jet black rises to the skies It reflects hatred in my eyes Feeling such a pain to die now Being a hungry wolf Crying under the moonlight`s shadow Sensing you'),
	(2, 'The time has come Goddess forsaken, a distant memory for mankind Thousand of years confined in lethargy away from the conscience Open your eyes and wake up, behold this betrayal, for those whom you gave life forgot you, it`s time for them to die! Rise and fall, it`s time to be born again Fire will rain, the end will soon begin The time has come! Ancient heralding revives deep within your guts, unconscious spark of life imperceptible to human eyes. The broken bond will never heal, we`re under nature`s will. Our future seems so dark, there is no turning back! Rise and fall, it`s time to be born again Fire will rain, the end will soon begin The time has come Empires crumble, when nature awakes! The black storm is coming I hear the sound of death Dark thunders are blasting above the mankind skies Rain falls from the heavens water soon will drown our lives The fury of nature will drench our souls Now... Rise and fall, it`s time to be born again. Fire will rain, the end will soon begin. The time has come. Empires crumble, when nature awakes! '),
	(3, 'Down to the south they migrate, I`m watching down below Desire burning my heart, I cannot fly I`m standing on the shore, birches are waiting naked Heavenly broom of winter has swept their leaves Nothing - left for me Tones of grey - are all I can see Eastern wind is tenderly fingering My cheekbones And on the lake On the foam-crested waves Grandfather frost Is riding So I`m going back to the Windlake Into the eye of the harsh gale Once and again to the Windlake Forever she`s calling my name I say farewell to summer, and winterize my boat Onto the wooden horses, I put it up to rest And to the draining water, I will turn my back But along the icy cover, I will come back Nothing - left for me Tones of grey - are all I can see My feet cold, my hands are stiffed My snot and tears are taken up Taken, taken up by the wind The wind tells my tale - Windlake Tale The wind tells my tale - Windlake Tale Windlake Tale, Windlake Tale So I`m going back to the Windlake Into the eye of the harsh gale Once and again to the Windlake Forever she`s calling my name'),
	(4, 'A king has summoned all the lords and powers of the realm A harvest feast to celebrate the bounties of the year Men pack the halls and women flock, to entertain the mass They feast and drink and fornicate, for winter`s nearly here The king stands all and welcomes all, raising a glass of cheer He bids his men to feast away and drink Drink until the dawn Tales of old are boldly told, by torchlight burning bright The quests and deeds of yesterday, we will relive tonight Welcome all to the gathering of kings Fill your stein As our time passes by Raise your glass into the sky Pound it back for those who have died Drink hard For the kingdom is ours tonight The autumn sun will rise and fill the halls of darkened souls In company of friends we drink and remember ones we lost The year`s been hard, men battle-scarred, we carry through their days But now we celebrate their lives and drink Drink until the dawn'),
	(5, 'SPELL OF THE IMMORTAL OPENS UP THE HELLS PORTAL RIPPING DOWN THE BLOODSTAINED CURTAIN SEPARATING LIFE FROM DEATH INSIDE THE NECROTORRENT ECHO CRIES OF THE TORMENTED THEY GROW MORE AND MORE ABHORRENT THE NETHERWORLD IS NEAR I DROWN INTO OBLIVION AND MEET THE CREATURE KNOWN AS DEATH I GIVE MY BODY TO MY MASTER KNEEL BEFORE THE SOUL HARVESTER CAN YOU SMELL IT, THE STENCH MERGED WITH BLOOD? THE REEK OF IRON, THE REEK OF REAPER`S SCYTHE MAKE ME FEEL IT, MAKE ME FEEL ALIVE AGAIN MAKE ME FEEL THE WRATH, THE WRATH OF REAPER`S SCYTHE MASTER OF THE DARK ARTS BORN FROM EVIL INSIDE MEN`S HEARTS THE EMBODIMENT OF CHAOS SUMMONS FORTH THE SOULS OF DEAD I`M NOW IN HIS POSSESSION I AM HIS CARNAL VESSEL DIMENSIONAL TRANSMISSION HIS EGRESS FROM THIS REALM'),
	(6, 'Follow the dead in the dark of damnation Pious in head & a demon at heart Sworn to the night An Evangelist nation born Under the sign of the dark Gather the wild Form the horde of the brave men Brothers allied Fight the storm of this curse Banners up high As we rise like a nation sworn All of the light we inverse Combat ahead & the night calls for heroes Ready for fire command Revel in red Come and wake up To bring no remorse Stand up as force Rise over the dead Bring us ahead Incense & Iron Fight all of the night Banners up high To the top of the land Right into the red All you can get Incense & Iron Stand, Follow the fight Doing the right As we come to defend Hollow the damned In the art of salvation Fallen & banned And the Angels die first Servant in life And elated in Heaven cursed Slaves in the light from beyond Bury the night in Imperial hunger Do or die in this fortress of fear Cannot deny All the wonders are sacred burst Under the weight of this world Remedy sent And the sky falls in treason Torn by the liar`s intend Devil in head Come and Break out And raise up the sword Stand up as horde  Rise over the dead Bring us ahead Incense & Iron Fight all of the night Banners up high To the top of the land Right into the red All you can get Incense & Iron  Stand, Follow the fight Doing the right As we come to defend When we all stand together Rise over the dead Bring us ahead Incense & Iron Fight all of the night Banners up high To the top of the land Right into the red All you can get Incense & Iron Stand, Follow the fight Doing the right As we come to defend When we will last forever'),
	(7, 'To the south there’s a city, ruled by a serpent-tongue Spinning his lies and tales, blinding everyone When I come to end this tyrant, he spouts words of silken twine Winding me in vapours, mystifying, clouding up my mind Then I recall words of warning said by my master Never allow for his enchantments to penetrate Know his weakness is my strength; overcome this haze Overlord your reign is at an end Your false walls are crumbling within Oppressor your spell has come undone Defy no more, imposter, overlord Once I see through the veil he has conjured out of dust Trapping his followers in a world they cannot trust Like a curtain hangs his doctrine, enslaving all who hear I must destroy this web, free the people, alleviate their fear As though a fog has been lifted, cries echo around us And like his brother before him I feel no remorse He will lie upon the altar, a well-deserving course You conjure your false walls Imposter, you surround us Your serpent tongue is enslaving everyone Oppressor, overlord Your doctrine, just vapours Your lies are leading the lost I will end you here'),
	(8, 'Haunted by the shadows of the past A owling void in my mind Through the halls of Kaer Morhen it echoes A remnant of memories left behind All I have are the swords on my back I wander but my purpose is clear White Wolf, Vatt`ghern, Butcher they call me I am the beast that the beasts will fear The flames of my eyes set ablaze Like the silence that burns in my heart  I will not stray from the code of my order Ride the Path By steel, by silver I slay like a wolf in the night By steel, by silver I slay, runes of power be my light By steel, by silver I slay like a wolf in the nightBy steel, by silver I slay, for the wolf is I Solitude, my companion on the Path Though I am shunned I am free For the failings of civilization Have proven more savage than any beast As the fires of Novigrad roar And the stakes of hypocrisy burn I have felt the hammer of prejudice Cast by humanity down from its throne The flames of my eyes set ablaze Like the silence that burns in my heart I will not stray from the code of my order Ride the Path By steel, by silver I slay like a wolf in the night By steel, by silver I slay, runes of power be my light By steel, by silver I slay like a wolf in the night By steel, by silver I slay, for the wolf is I Fear this night Silver is light, be my guide Ride out across the Temerian plains Ride into bloodshed, forever be changed Dark visions haunt me from cold cosmic realms Winter eternally reigns Clad in black iron with hoods rimed in frost  Weilding black magicks form dark spheres beyond Legions of spectres take fleght in the sky Winter eternally reigns By steel, by silver I slay like a wolf in the night By steel, by silver I slay, runes of power be my light By steel, by silver I slay like a wolf in the night By steel, by silver I slay, for the wolf is I'),
	(9, 'The night of timeless fire is drawing near I flee, throughout the years of throe Watching through a mirror, as I fall apart I see a wreck, I`m burning I see angels burning, falling down in ruins Looking down I see me, I`m my own enemy Watching myself decaying, falling from high spirits I flee, throughout the ruins of me Longing for finding my way out Leaving myself, there`s nothing left for me The ruins are about to crumble down. The flame is dying by shivery winds of jet black skies It reflects hatred in my eyes I see angels burning, falling down in ruins Looking down I see my ashes scattered around my grave Angels whispering fire, no longer I`m alive Settled down I`m done with the trip to my kingdom come'),
	(10, 'A man on the corner with glassy look Telling a story of his lifetime A thousand times told, desperate verse But never listened Another on by the bar talking to a barmaid Has spent his whole life there A naively trusting man never faced life Or has just found Eldorado Life is nothing but a gift... Poor human fates Pure human fakes No human rights The underrated The third one by the table never said a word Gazing into the distance The observer, melancholic man  Just drinking heavily Not very old but still a veteran Has lost his thread of life In god-forsaken place they are the family And they are at home Life is nothing but a gift... Use of education is not complete solution Now it is time to look in the mirror'),
	(11, 'Stand up all the night and call the fight Let your mind go wild before the light Here we come the army of the night Mater Maria Lined up side by side and bound to pray Sent do die and fight the final day Army of the night - we came to stay Mater Maria Better you pray before the night is falling Call on the heaven sent, amen Follow the night, it`s your messiah calling Bring on the sacrament, amen Come to the other side Into the dark we hide Gather them for rite Sacristarum We are the force allied Into the War we ride Halleluja Enemies falling when the sermon spoken Taken by higher hand, amen Hallow the martyrs when the bible broken Summon the testament, amen Sanctify the night for all the time Break the bread and raise the holy wine Army of the night - go walk the line Mater Maria'),
	(13, 'Falling through the cracks within my mind I hold the answer inside Not all that I could be but this is my declaration I know the path that`s ahead My influence will be widespread  I`ll live in infamy Your future is my detainee  Crossing the seas, the tides splash upon our bow; We emerge upon their shores. Our defeat we`ll not allow Wounded by the archers` airstrike, we sail towards the storm; Leaving fallen ones behind to be washed upon the shore. Stricken by the loss of battle, redemption soon will soar;  Seeking freedom and salvation, winds guide us back for more.  The pain I did define The plan was indeed malign I stand here and draw my line The final goal is all combined No matter what you`re not alone I promise that they`ll all be shown When we set foot upon their land That they will disband, off-hand, and if I only understand Crossing the seas, the tides splash upon our bow,  We emerge upon their shores, our defeat we`ll not allow This is our declaration Approach with fire in hand Squeeze the life from all in sight My goal is their plight We crash upon their fields We`re fast on their heels Our midnight gods will revel in their folly But their cries for love Will be burnt from above Magic will shine off our knives, for the rest of our lives '),
	(14, 'Pulling the last cry, I was alive (alive!) While I`m down in my hatred, weird, right (right!) Your god has set you on fire, in the day you`re dark your way When we reached this final dusk Then bring me fire and insanity The jet-black eyes are showing butterflies, They dance in the fire insane, so Fire: dance with me Fire: come with me Fire: your fire Of the everlasting flame, did burn me; The one we are all off often struggling down, down, down, down And when you hear me forth to the everlast, Hear me used to bear dreams cast in a silent near Fire: you`re killing me Fire: a thorn, sweet, so rare We`ll praise the Lord to begin it Until the others will fall But, victims are we all We will at last destroy human gods And within us the fire is burning The dream lives forth and we`re standing strong to fight And the everlasting fire is burning Fire: come with me Fire: my god is with me Fire: together (forever)'),
	(15, 'To look up into the night’s sky, to see the stars they are changed To know a thousand years or more have passed, and I am the same This mountain hollow that keeps me in a suffocating embrace A prison and a safe haven, it’s always been this way Lo, a new master calls me to awakening, I know this one brings the end Far out beyond the darkness I’ve been living in it’s true, a whole new world awaits Stellar constellations rise, lighting my way in the night Once again revitalized, to roam; to never die My path begins with the new dawn; a voice is calling my name It always starts as whispering then manifests to a scream I’m drawn to the creature that wakes me, bound to them by the curse My soul exists only to serve, a covenant of birth Fear not the task ahead there’s no escaping it, there’s no good nor evil here Come to me, awakening Follow my voice, come to me Fear not the task ahead there’s no escaping it, there’s no good nor evil here');

insert into genre (name) values
	('Melodic Death Metal'),
	('Power Metal'),
	('Heavy Metal'),
	('Thrash Metal'),
	('Black Metal'),
	('Death Metal'),
	('Speed Metal'),
	('Symphonic Metal'),
	('Folk Metal');

insert into band_genre (band_id, genre_id) values
	(1, 1), (1, 2), (1, 4),
	(2, 1), (2, 2), (2, 9),
	(3, 1), (3, 2),
	(4, 1), (4, 2),
	(5, 4), (5, 5),
	(6, 2),
	(7, 2),
	(8, 2), (8, 3);
